name: spreadsheet
version: '0.1.0.0'
synopsis: Model a spreadsheet
description: Model a spreadsheet
category: Game
author: Franklin Chen
maintainer: franklinchen@franklinchen.com
copyright: Franklin Chen
license: BSD3
github: FranklinChen/spreadsheet-haskell
ghc-options: -Wall
extra-source-files:
- README.md
dependencies:
- base >=4 && <=5
library:
  source-dirs: src
tests:
  spec:
    defaults: hspec/hspec@master
    main: Spec.hs
    source-dirs: test
    dependencies:
    - spreadsheet
    - hspec
    - QuickCheck
